-- TABLE
CREATE TABLE demo (ID integer primary key, Name varchar(20), Hint text );
CREATE TABLE EMPLEADO (
ID INT(8),
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(59),
  SEXO CHAR(1),
FECHA_NACIMIENTO DATE,
SALARIO DOUBLE(10,2)
);
CREATE TABLE VACACIONES(
ID INT(8),
ID_EMP INT(8),
FECHA_INICIO DATE,
FECHA_FIN DATE,
ESTADO CHAR(1),
CANTIDAD_DIAS INT(8)
);
 
-- INDEX
 
-- TRIGGER
 
-- VIEW
 
